### PR TITLE
Create InvertBinaryTree.cpp

### PR DESCRIPTION
**Pull request by AnushkaSingh1**

### CODE REVIEW

**Comment by princeroshanantony** [comment]
Who is this? I don't think I know you?

**Comment by AnushkaSingh1** [comment]
I thought it was for hacktoberfest!
I just randomly did my open source contribution.

**Comment by princeroshanantony** [comment]
Anushka, you should atleast leave a comment or description of what changes or something about the new code you contributed. Yes, I am accepting PRs for hacktoberfest. Kindly do the same in a new PR.

**Comment by AnushkaSingh1** [comment]
Will do, thanks!

**Pull request closed without merging**
